name: Build EPUB

on: push

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up matrix
        id: set-matrix
        run: |
          cd $GITHUB_WORKSPACE
          echo "::set-output name=matrix::[$(find . -type f -name 'build.sh' -printf '"%h"\n' | paste -s -d, -)]"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  build-epub:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        book-dir:
          ${{fromJson(needs.prepare.outputs.matrix)}}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Pandoc installation
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.18'

      - name: Build EPUB
        run: |
          cd $GITHUB_WORKSPACE/${{ matrix.book-dir }}
          bash build.sh

      - name: Upload EPUB
        uses: actions/upload-artifact@v3
        with:
          path:
            _out/*.epub
          name: epub
