name: Build EPUB

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    tags:
      - Book*


jobs:
  build-epub:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Pandoc installation
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.18'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Set up Cargo Bin Install
        run: |
          export PATH="$PATH:$HOME/.cargo/bin"
          wget https://github.com/ryankurte/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-gnu.tgz
          tar xf cargo-binstall-x86_64-unknown-linux-gnu.tgz --directory=$HOME/.cargo/bin

      - name: Set up Cache
        uses: Swatinem/rust-cache@v1

      - name: Set up MDBook EPUB installation
        run: |
          cargo-binstall mdbook --no-confirm
          cargo install --git https://github.com/glatavento/mdbook-epub

      - name: Build EPUB
        run: |
          cd $GITHUB_WORKSPACE/
          for dir in *; do
            if [ -d "$dir" ]; then
              cd "$dir"
              if [ -f "build.sh" ]; then
                bash ./build.sh
              fi
              cd ..
            fi
          done

      - name: Upload EPUB
        uses: actions/upload-artifact@v3
        with:
          path:
            _out/*.epub
          name: epub
